name: CI Pipeline

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:

  validate_commit_messages:
    uses: woped/devops/.github/workflows/validate-commit-msg.yaml@main

  linting:
    uses: woped/devops/.github/workflows/linting.yaml@main

  testing_flask:
    with:
      flask_app: llm-api-connector.py
      flask_env: testing
    uses: woped/devops/.github/workflows/testing_flask.yaml@main

  sonar_python:
    needs: testing_flask
    uses: woped/devops/.github/workflows/sonar_flask.yaml@main
    secrets: inherit
