name: CI Pipeline

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  validate_commit_messages:
    uses: woped/devops/.github/workflows/validate-commit-msg.yaml@main

  linting:
    uses: woped/devops/.github/workflows/linting.yaml@main
  testing_flask:
    with:
      FLASK_APP: llm-api-connector.py
    uses: woped/devops/.github/workflows/testing_pyflask.yaml@main
  sonar_python:
    needs: testing_flask
    uses: woped/devops/.github/workflows/sonar_python.yaml@main
    secrets: inherit
